### PR TITLE
Julie.Adams.SA

### PR DESCRIPTION
**Pull request by lareinajul**
## Checkpoint Rubric
This is the rubric that your instructor will use to grade your checkpoints. Please do not edit. 

**Checkpoint 1**
- [ ] A CSS file is effectively linked to the HTML file in the Head section: 15 points
- [ ] A link to a CSS reset file is included in the Head section of the HTML file: 15 points 
- [ ] Appropriate use of Semantic Elements: 15 points
- [ ] Effective use of box model: 15 points
- [ ] Proper use of documentation (commenting on code): 15 points
- [ ] The student demonstrated mastery of HTML/CSS by building a website of professional caliber: 25 points

**Checkpoint 2**
- [ ] Effective use of Flexbox layout: 15 points
- [ ] Responsive site (resizes to fit desktop, tablet, and mobile views): 15 points 
- [ ] Effective use of Bootstrap Grid: 15 points
- [ ] Proper use of documentation (commenting on code): 15 points
- [ ] Site is hosted on github: 15 points
- [ ] The student demonstrated mastery of HTML/CSS and Responsive Web Design by building a website of professional caliber: 25 points

**Checkpoint 3**
- [ ] Use of HTML: 15 points
- [ ] Use of CSS: 15 points
- [ ] Use of JQuery: 15 points
- [ ] Proper use of documentation (commenting on code): 15 points
- [ ] The application has a professional look: 15 points
- [ ] The application functions as it should: 25 points

### CODE REVIEW

**Comment by robinskj** [comment]
Checkpoint 1

 X  A CSS file is effectively linked to the HTML file in the Head section: 15 points
 X   Use of Google Fonts: 15 points
 x   Appropriate use of Semantic Elements: 15 points
 x   Effective use of box model: 15 points
 x   Proper use of documentation (commenting on code): 15 points
 x   The student demonstrated mastery of HTML/CSS by building a website of professional caliber: 25 points
100 pts total - great job!

Some Comments:
In your CSS file: 
You have some properties on the same line.  Although it is technically correct, it is harder to read.  Consider putting each property on its own line like this:<br>
color: black; 
text-align: center;
background-color: grey ;

At the top of the index.html file, you enclosed several lines inside an   h1> tag, with p> tags still inside the heading tag, so your writing at the very top comes out looking all the same.  I'm not sure if that's what you intended.  This is a stylistic choice, but I would have used maybe  h2> tags for the lower lines, so that the top line stands out a bit.

Using the box model, you can add some left and right padding to the p> tag in your css, so your writing in the index.html file doesn't show all the way to the very edge of the page.  Again, this is a stylistic choice, but it is more common to have that buffer of space at the edge of the page rather than have your writing go all the way to the edge.

These are just some helpful hints, you did a great job! - Kristina

**Comment by robinskj** [comment]
x Effective use of Flexbox layout: 15 points
-5pts Responsive site (resizes to fit desktop, tablet, and mobile views): 15 points
-15pts Effective use of Bootstrap Grid: 15 points
x Proper use of documentation (commenting on code): 15 points
x Site is hosted on github: 15 points
-5pt The student demonstrated mastery of HTML/CSS and Responsive Web Design by building a website of professional caliber: 25 points
Total: 75pts

Comments:
- The assignments requires responsive site for three sizes: desktop, tablet, and mobile views.  Your site coded for two sizes only, mobile and everything else.  That's why I took off 5 points.
- You did not use Bootstrap at all.  We covered an entire section on Bootstrap, how to reference small, medium and large column sizes, plus many other handy formatting shortcuts available through Bootstrap.  It requires linking to the Bootstrap style sheet.
- Your layout was quite nice for desktop view.  For mobile view however, the background colors in the lower panels were uneven.  You had some grey and some white.

Overall. nice work.  If you had used Bootstrap you would have had an excellent score!

**Comment by lareinajul** [comment]
Thanks for the feedback.. I finished moving this weekend.. not the best of circumstances but I am moved and closer to work.. and starting this weekend should be catching up on everything.


I will revisit the project and add the bootstrap, and go over all my projects and take time to re review all the tutorials and everything in Intro..


I plan to spend the next few weekends reviewing everything we did.


Appreciate your feedback and thanks for the help!!


Julie


________________________________

**Comment by robinskj** [comment]
Checkpoint 3   
x Use of HTML: 15 points  
x Use of CSS: 15 points  
-15 Use of JQuery: 15 points  
-15 Proper use of documentation (commenting on code): 15 points  
x The application has a professional look: 15 points  
x The application functions as it should: 25 points
--
Wonderful and original app Julie!

**Pull request closed without merging**
