### PR TITLE
Jacqueline.Earhart.SA

### PR DESCRIPTION
**Pull request by j-earhart**
## Checkpoint Rubric
This is the rubric that your instructor will use to grade your checkpoints. Please do not edit. 

**Checkpoint 1**
- [ ] A CSS file is effectively linked to the HTML file in the Head section: 15 points
- [ ] A link to a CSS reset file is included in the Head section of the HTML file: 15 points 
- [ ] Appropriate use of Semantic Elements: 15 points
- [ ] Effective use of box model: 15 points
- [ ] Proper use of documentation (commenting on code): 15 points
- [ ] The student demonstrated mastery of HTML/CSS by building a website of professional caliber: 25 points

**Checkpoint 2**
- [ ] Effective use of Flexbox layout: 15 points
- [ ] Responsive site (resizes to fit desktop, tablet, and mobile views): 15 points 
- [ ] Effective use of Bootstrap Grid: 15 points
- [ ] Proper use of documentation (commenting on code): 15 points
- [ ] Site is hosted on github: 15 points
- [ ] The student demonstrated mastery of HTML/CSS and Responsive Web Design by building a website of professional caliber: 25 points

**Checkpoint 3**
- [ ] Use of HTML: 15 points
- [ ] Use of CSS: 15 points
- [ ] Use of JQuery: 15 points
- [ ] Proper use of documentation (commenting on code): 15 points
- [ ] The application has a professional look: 15 points
- [ ] The application functions as it should: 25 points

### CODE REVIEW

**Comment by robinskj** [comment]
X  A CSS file is effectively linked to the HTML file in the Head section: 15 points
X  A Google Font is used effectively: 15 points
 -5 Appropriate use of Semantic Elements: 15 points
x Effective use of box model: 15 points
X  Proper use of documentation (commenting on code): 15 points
x The student demonstrated mastery of HTML/CSS by building a website of professional caliber: 25 points

Comments:
Beautiful styling!  
(-5pts) Slight problem in structuring your semantic elements.  You have an unordered list as your menu in the head> tag.  The head tag is only for linking style sheets, your title tag, and meta data tags.  Basically things that don't appear directly on your main screen.  The body> tag is where everything goes that shows up on your main view.  Navigation menus always appear inside body> tags.  Sometimes people choose to put them inside the header tag, sometimes people choose to put them inside a nav> tag, and sometimes people just put them inside a div>.  It's totally up to you.  However, it will fail validation if you put it inside the head> tag as you did.

Another small suggestion for on down the road.  When you have a logo in the navigation, users frequently expect that to be clickable, and that it will load the Home screen.  Just something to think about when you are designing screens for the long term.

**Comment by robinskj** [comment]
x Effective use of Flexbox layout: 15 points
-5pts Responsive site (resizes to fit desktop, tablet, and mobile views): 15 points
x Effective use of Bootstrap Grid: 15 points
x Proper use of documentation (commenting on code): 15 points
x Site is hosted on github: 15 points
x The student demonstrated mastery of HTML/CSS and Responsive Web Design by building a website of professional caliber: 25 points
 Total points: 95

Beautiful!
Comments:
The assignment calls for responsive resizing for 3 sizes: desktop, mobile, and tablet.  We discussed in class using "@media" queries to determine screen sizes, and using different css layouts, or styles etc, for different screen sizes.  You effectively used Bootstrap to responsively resize for mobile screens vs desktop, but there is no special styling for tablets.  That's why I took off the 5 points.   You could have also have used Bootstrap classes for col-m rather than the media query css to address the tablet layout.

Otherwise, very well done!

**Comment by robinskj** [comment]
x Use of HTML: 15 points
x Use of CSS: 15 points
x Use of JQuery: 15 points
-15pts  Proper use of documentation (commenting on code): 15 points
x The application has a professional look: 15 points
x The application functions as it should: 25 points

Good application!

**Comment by robinskj** [comment]
Checkpoint 3

x    Use of HTML: 15 points
x    Use of CSS: 15 points
x    Use of JQuery: 15 points
x    Proper use of documentation (commenting on code): 15 points
x   The application has a professional look: 15 points
x    The application functions as it should: 25 points

100 pts

Excellent!!

**Comment by j-earhart** [comment]
What is this?

**Comment by kevincolten** [comment]
This is your Pull Request from class last year. We close them when we are done to help organize for new students. All of your code and this PR is still there, it's just marked as closed.

**Pull request closed without merging**
